name: Apply schema migrations

# 👉 Only run this workflow when a change is made to the main branch
on:
  push:
    branches:
      - main

jobs:
  apply_migrations:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.11.0]
        pnpm-version: [9.9.0]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm ${{ matrix.pnpm-version }}
        uses: pnpm/action-setup@v3
        with:
          version: ${{ matrix.pnpm-version }}

      - name: Create .env file
        run: |
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} > .env |
          echo AUTH_TOKEN=${{ secrets.AUTH_TOKEN }} > .env

      - name: Install dependencies
        run: pnpm i

      - name: Apply migrations
        run: pnpm db:migrate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
